project_name: label-watch
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
dockers:
- image_templates:
   - "kolikons/{{.ProjectName}}:{{ .Version }}"
   - "kolikons/{{.ProjectName}}:latest"
  dockerfile: Dockerfile
  goos: linux
  goarch: amd64
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/kolikons/label-watch
  - --label=org.opencontainers.image.source=https://github.com/kolikons/label-watch
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - "--label=org.opencontainers.image.created={{.Date}}"
