{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "app.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "app.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "app.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
