
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "app.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "patch"]
{{- end -}}
