apiVersion: v2
name: label-watch
description: label-watch checks a specific label on worker node then create an label
type: application
maintainers:
  - name: kolikons
    url: https://github.com/kolikons/label-watch
sources:
  - https://github.com/kolikons/label-watch
version: 1.0.0
appVersion: "0.1.0"
