apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: label-watch
  name: label-watch
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: label-watch
  template:
    metadata:
      labels:
        app: label-watch
    spec:
      serviceAccountName: label-watch
      restartPolicy: Always
      containers:
        - name: label-watch
          args:
            - -interval
            - 30m
            - -label
            - node-type
          image: kolikons/label-watch:0.1.0
          imagePullPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: label-watch
  namespace: default
  labels:
    app: label-watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: label-watch
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: label-watch
subjects:
  - kind: ServiceAccount
    name: label-watch
    namespace: default
roleRef:
  kind: ClusterRole
  name: label-watch
  apiGroup: rbac.authorization.k8s.io
