name: Go Build & Test
on:
  pull_request:
    paths:
      - "pkg/**"
jobs:
  init-cancel-workflow:
    name: "Cancel Previous Runs"
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0

  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Build & Test
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/setup-go@v5
        with:
          go-version: 1.18

      - run: go mod download

      - name: Build & Test
        run: |
          go build -v .
          go test ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --snapshot --clean --skip=publish,sign
